packages:
  - packages/*
allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  dprint: false
  esbuild: false
  msgpackr-extract: false
  vue-demi: false
overrides:
  date-fns: ^4.4.0
  fast-check: ^4.8.0
  vue: ^3.5.35
patchedDependencies:
  ts-plugin-sort-import-suggestions: patches/ts-plugin-sort-import-suggestions.patch
  "@tanstack/query-core": patches/@tanstack__query-core.patch
  typescript@6.0.3: patches/typescript.patch
  "@sendgrid/mail": patches/@sendgrid__mail.patch
