packages:
  - packages/*
overrides:
  typescript: 6.0.3
allowBuilds:
  "@parcel/watcher": false
  better-sqlite3: true
  dprint: true
  esbuild: true
  msgpackr-extract: false
  vue-demi: false
patchedDependencies:
  ts-plugin-sort-import-suggestions: patches/ts-plugin-sort-import-suggestions.patch
  "@tanstack/query-core": patches/@tanstack__query-core.patch
  typescript@6.0.3: patches/typescript.patch
  "@sendgrid/mail": patches/@sendgrid__mail.patch
